name: "Automated API and E2E tests (Playwright)"

on: push

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to tests repository"
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}
          ref: ${{github.ref}}
      - name: "Copy env variables"
        run: |
          cp '.env.example' '.env'
      - name: "Run API tests"
        env:
          BASE_URL: 'https://qauto.forstudy.space/'
          HTTP_CREDENTIALS_USERNAME: ${{secrets.HTTP_CREDENTIALS_USERNAME}}
          HTTP_CREDENTIALS_PASSWORD: ${{secrets.HTTP_CREDENTIALS_PASSWORD}}
        run: |
          docker compose up --exit-code-from api-tests
      - name: "Upload API report to artifacts"
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: playwright-report/
          retention-days: 3


  e2e-tests:
    runs-on: ubuntu-latest
    needs: [api-tests]
    steps:
      - name: "Checkout to tests repository"
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}
          ref: ${{github.ref}}
      - name: "Copy env variables"
        run: |
          cp '.env.example' '.env'
      - name: "Run E2E tests"
        env:
          BASE_URL: 'https://qauto.forstudy.space/'
          HTTP_CREDENTIALS_USERNAME: ${{secrets.HTTP_CREDENTIALS_USERNAME}}
          HTTP_CREDENTIALS_PASSWORD: ${{secrets.HTTP_CREDENTIALS_PASSWORD}}
        run: |
          docker compose up --exit-code-from e2e-tests
      - name: "Upload E2E report to artifacts"
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report
          path: playwright-report/
          retention-days: 3
